### PR TITLE
Feature/getters

### PR DESCRIPTION
**Pull request by janstarke**
# Changes
 - use `getset` to automatically `Getters` to be able to access atomic data from lnk files
 - use CP1252 instead of UTF-8 to decode non-unicode strings

### CODE REVIEW

**Comment by janstarke** [comment]
I'm going to use the updated version of this crate in <https://github.com/janstarke/lnk2bodyfile>. Feel free to fiddle around with this tool and discuss my changes before merging it ;-)

Thanks anyway for your great work so far :+1:

**Comment by AbdulRhmanAlfaifi** [comment]
Hi,
I have `lnk` samples in the directory `samples` with different `lnk` types. The samples are from three different Windows versions containing different data:
* Windows generated `lnk` for local file
* Manually created `lnk` for local file
* Windows generated `lnk` for remote file (in remote share)
For files in two languages English & Arabic.

I tested the samples with `UTF-8` & `CP1252` and they both output the correct results. Do you have the `lnk` file with the encoding error? 

I have `test` cases already setup for all `lnk` files in the `samples` directory. Just drop your `lnk` file in the appropriate directory (WIN7, WIN10, etc) and run the test command:
```bash
cargo test -- --nocapture
``` 
and share the results for the `UTF-8` & `CP1252`. Or just share the `lnk` files here and I will do the testing. I want to make sure it doesn't effect any other strings in `lnk` files.

Thanks!

**Comment by janstarke** [comment]
I added two `lnk` files from a Windows system I can use, and the tests run fine on my system. I'm curious if this will work on yours as well...

**Comment by AbdulRhmanAlfaifi** [comment]
Hi,
It worked on on both string encodings `UTF-8` & `CP1252`. I am going to do couple more test and if it worked I am going to merge this to master

**Comment by AbdulRhmanAlfaifi** [comment]
Hi,
I tested couple more `lnk` files for different languages and I didn't face any issues. I am going to merge this pull request to master. Please let me know if you faced any issues with the encoding.

Thank you for your contribution!

**Comment by janstarke** [comment]
Thanks a lot. Your work enabled me to publish [lnk2bodyfile](https://crates.io/crates/lnk2bodyfile) :-)

**Pull request merged**
